# Generated by Django 5.2.4 on 2025-08-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cameras_accidents_today_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='vehicle_counter',
            field=models.IntegerField(default=0),
        ),
    ]
