# Generated by Django 5.2.4 on 2025-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRecorded',
            fields=[
                ('id_x', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='transports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
