# Generated by Django 5.2.4 on 2025-07-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_accesskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='access_key_1',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='access_key_2',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
