# Generated by Django 5.2.4 on 2025-08-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id_x', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('camera_name', models.CharField(default='Unnamed', max_length=255)),
                ('kinesis_datastream_name', models.CharField(max_length=255)),
                ('visited_counter', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
