# Generated by Django 5.2.4 on 2025-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id_x', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('camera_name', models.CharField(default='Unnamed', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
