# Generated by Django 5.2.4 on 2025-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_datastream'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id_x', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('call_from', models.CharField(default='Unnamed', max_length=255)),
                ('call_to', models.CharField(default='Unnamed', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
