# Generated by Django 5.2.4 on 2025-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='accidents_today_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameras',
            name='accidents_total_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameras',
            name='danger_alarm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameras',
            name='emergency_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameras',
            name='exlamacion_alarm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameras',
            name='info_alarm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameras',
            name='sqs_name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
    ]
