# Generated by Django 5.2.4 on 2025-07-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_usersrecorded_webauthncredential_transports'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id_x', models.AutoField(primary_key=True, serialize=False)),
                ('access_key_1', models.CharField(max_length=500)),
                ('access_key_2', models.CharField(max_length=500)),
            ],
        ),
    ]
