# Generated by Django 5.2.4 on 2025-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_accesskey_access_key_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrecorded',
            name='id_x',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usersrecorded',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
