# Generated by Django 5.2.4 on 2025-08-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_usersrecorded_id_x_alter_usersrecorded_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersrecorded',
            old_name='user',
            new_name='email',
        ),
        migrations.AddField(
            model_name='usersrecorded',
            name='name',
            field=models.CharField(default='unknown@no-organization.com', max_length=255, unique=True),
        ),
    ]
