# Generated by Django 5.2.4 on 2025-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_rename_user_usersrecorded_email_usersrecorded_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential_UsersRecorded',
            fields=[
                ('id_x', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_user', models.CharField(max_length=500, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='id_x',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
