# Generated by Django 5.2.4 on 2025-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_webauthncredential_usersrecorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrecorded',
            name='name',
            field=models.CharField(default='unknown@no-organization.com', max_length=255),
        ),
    ]
